online_test/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz.admin import custom_admin_site

# from quiz.views import main_page


urlpatterns = [
    path("admin/", custom_admin_site.urls),
    # path('main/', main_page, name='main-page'),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import include, re_path, path
from .views import *


urlpatterns = [
    re_path(r"^$", view=index, name="index"),
    re_path(r"^login$", view=login_user, name="login"),
    re_path(r"^dsa/$", view=dsa, name="dsa"),
    re_path(r"^dsa1/$", view=dsa1, name="dsa1"),
    re_path(r"^dsa2/$", view=dsa2, name="dsa2"),
    re_path(r"^dsa3/$", view=dsa3, name="dsa3"),
    re_path(r"^dsa4/$", view=dsa4, name="dsa4"),
    re_path(r"^dsa5/$", view=dsa5, name="dsa5"),
    re_path(r"^dsa6/$", view=dsa6, name="dsa6"),
    re_path(r"^os/$", view=os, name="os"),
    re_path(r"^os1/$", view=os1, name="os1"),
    re_path(r"^os2/$", view=os2, name="os2"),
    re_path(r"^os3/$", view=os3, name="os3"),
    re_path(r"^os4/$", view=os4, name="os4"),
    re_path(r"^os5/$", view=os5, name="os5"),
    re_path(r"^sql/$", view=sql, name="sql"),
    re_path(r"^sql1/$", view=sql1, name="sql1"),
    re_path(r"^sql2/$", view=sql2, name="sql2"),
    re_path(r"^sql3/$", view=sql3, name="sql3"),
    re_path(r"^sql4/$", view=sql4, name="sql4"),
    re_path(r"^sql5/$", view=sql5, name="sql5"),
    re_path(r"^toc/$", view=toc, name="toc"),
    re_path(r"^toc1/$", view=toc1, name="toc1"),
    re_path(r"^toc2/$", view=toc2, name="toc2"),
    re_path(r"^toc3/$", view=toc3, name="toc3"),
    re_path(r"^toc4/$", view=toc4, name="toc4"),
    re_path(r"^toc5/$", view=toc5, name="toc5"),
    re_path(r"^cn/$", view=cn, name="cn"),
    re_path(r"^cn1/$", view=cn1, name="cn1"),
    re_path(r"^cn2/$", view=cn2, name="cn2"),
    re_path(r"^cn3/$", view=cn3, name="cn3"),
    re_path(r"^cn4/$", view=cn4, name="cn4"),
    re_path(r"^cn5/$", view=cn5, name="cn5"),
    re_path(r"^cn6/$", view=cn6, name="cn6"),
    re_path(r"^signup$", view=signup_user, name="signup"),
    re_path(r"^Go/$", view=Go, name="Go"),
    re_path(r"^logout/$", view=logout_user, name="logout"),
    re_path(r"^quizzes/$", view=QuizListView.as_view(), name="quiz_index"),
    re_path(
        r"^category/$", view=CategoriesListView.as_view(), name="quiz_category_list_all"
    ),
    re_path(
        r"^category/(?P<category_name>[\w|\W-]+)/$",
        view=ViewQuizListByCategory.as_view(),
        name="quiz_category_list_matching",
    ),
    re_path(r"^progress/$", view=QuizUserProgressView.as_view(), name="quiz_progress"),
    re_path(r"^marking/$", view=QuizMarkingList.as_view(), name="quiz_marking"),
    re_path(
        r"^marking/(?P<pk>[\d.]+)/$",
        view=QuizMarkingDetail.as_view(),
        name="quiz_marking_detail",
    ),
    #  passes variable 'quiz_name' to quiz_take view
    re_path(
        r"^(?P<slug>[\w-]+)/$", view=QuizDetailView.as_view(), name="quiz_start_page"
    ),
    re_path(
        r"^(?P<quiz_name>[\w-]+)/take/$", view=QuizTake.as_view(), name="quiz_question"
    ),
    re_path(
        r"^quiz/redirect_to_admin/$", view=redirect_to_admin, name="redirect_to_admin"
    ),
    re_path(r"^admin$", view=admin, name="admin"),
]

quiz/models.py
import re
import json
import csv
from django.db import models
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import (
    MaxValueValidator,
    validate_comma_separated_integer_list,
)
from django.utils.timezone import now
from django.conf import settings
from django.utils.translation import ugettext as _
from model_utils.managers import InheritanceManager
from django.db.models.signals import pre_save, post_save
import io
from .signals import csv_uploaded
from .validators import csv_file_validator
from django.contrib.auth.models import User
from django.contrib import messages


class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub(r"\s+", r"-", category).lower())
        new_category.save()
        return new_category


class Category(models.Model):

    category = models.CharField(
        verbose_name=_("Category"), max_length=250, blank=True, unique=True, null=True
    )

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.category


class Quiz(models.Model):

    title = models.CharField(verbose_name=_("Title"), max_length=60, blank=False)

    description = models.TextField(
        verbose_name=_("Description"),
        blank=True,
        help_text=_("a description of the quiz"),
    )

    url = models.SlugField(
        max_length=60,
        blank=False,
        help_text=_("a user friendly url"),
        verbose_name=_("user friendly url"),
    )

    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        verbose_name=_("Category"),
        on_delete=models.CASCADE,
    )

    random_order = models.BooleanField(
        blank=False,
        default=False,
        verbose_name=_("Random Order"),
        help_text=_(
            "Display the questions in " "a random order or as they " "are set?"
        ),
    )

    max_questions = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name=_("Max Questions"),
        help_text=_("Number of questions to be answered on each attempt."),
    )

    answers_at_end = models.BooleanField(
        blank=False,
        default=False,
        help_text=_(
            "Correct answer is NOT shown after question."
            " Answers displayed at the end."
        ),
        verbose_name=_("Answers at end"),
    )

    exam_paper = models.BooleanField(
        blank=False,
        default=False,
        help_text=_(
            "If yes, the result of each"
            " attempt by a user will be"
            " stored. Necessary for marking."
        ),
        verbose_name=_("Exam Paper"),
    )

    single_attempt = models.BooleanField(
        blank=False,
        default=False,
        help_text=_(
            "If yes, only one attempt by"
            " a user will be permitted."
            " Non users cannot sit this exam."
        ),
        verbose_name=_("Single Attempt"),
    )

    pass_mark = models.SmallIntegerField(
        blank=True,
        default=0,
        verbose_name=_("Pass Mark"),
        help_text=_("Percentage required to pass exam."),
        validators=[MaxValueValidator(100)],
    )

    success_text = models.TextField(
        blank=True,
        help_text=_("Displayed if user passes."),
        verbose_name=_("Success Text"),
    )

    fail_text = models.TextField(
        verbose_name=_("Fail Text"), blank=True, help_text=_("Displayed if user fails.")
    )

    draft = models.BooleanField(
        blank=True,
        default=False,
        verbose_name=_("Draft"),
        help_text=_(
            "If yes, the quiz is not displayed"
            " in the quiz list and can only be"
            " taken by users who can edit"
            " quizzes."
        ),
    )

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        self.url = re.sub("\s+", "-", self.url).lower()

        self.url = "".join(
            letter for letter in self.url if letter.isalnum() or letter == "-"
        )

        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError("%s is above 100" % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def anon_score_id(self):
        return str(self.id) + "_score"

    def anon_q_list(self):
        return str(self.id) + "_q_list"

    def anon_q_data(self):
        return str(self.id) + "_data"


# progress manager
class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user, score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    """
    Progress is used to track an individual signed in users score on different
    quiz's and categories
    Data stored in csv using the format:
        category, score, possible, category, score, possible, ...
    """

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE
    )

    score = models.CharField(
        validators=[validate_comma_separated_integer_list],
        max_length=1024,
        verbose_name=_("Score"),
    )

    correct_answer = models.CharField(max_length=10, verbose_name=_("Correct Answers"))

    wrong_answer = models.CharField(max_length=10, verbose_name=_("Wrong Answers"))

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    @property
    def list_all_cat_scores(self):
        """
        Returns a dict in which the key is the category name and the item is
        a list of three integers.
        The first is the number of questions correct,
        the second is the possible best score,
        the third is the percentage correct.
        The dict will have one key for every category that you have defined
        """
        score_before = self.score
        output = {}

        for cat in Category.objects.all():
            to_find = re.escape(cat.category) + r",(\d+),(\d+),"
            #  group 1 is score, group 2 is highest possible

            match = re.search(to_find, self.score, re.IGNORECASE)

            if match:
                score = int(match.group(1))
                possible = int(match.group(2))

                try:
                    percent = int(round((float(score) / float(possible)) * 100))
                except:
                    percent = 0

                output[cat.category] = [score, possible, percent]

            else:  # if category has not been added yet, add it.
                self.score += cat.category + ",0,0,"
                output[cat.category] = [0, 0]

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        """
        Pass in question object, amount to increase score
        and max possible.
        Does not return anything.
        """
        category_test = Category.objects.filter(category=question.category).exists()

        if any(
            [
                item is False
                for item in [
                    category_test,
                    score_to_add,
                    possible_to_add,
                    isinstance(score_to_add, int),
                    isinstance(possible_to_add, int),
                ]
            ]
        ):
            return _("error"), _("category does not exist or invalid score")

        to_find = (
            re.escape(str(question.category)) + r",(?P<score>\d+),(?P<possible>\d+),"
        )

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:
            updated_score = int(match.group("score")) + abs(score_to_add)
            updated_possible = int(match.group("possible")) + abs(possible_to_add)

            new_score = ",".join(
                [str(question.category), str(updated_score), str(updated_possible), ""]
            )

            # swap old score for the new one
            self.score = self.score.replace(match.group(), new_score)
            self.save()

        else:
            #  if not present but existing, add with the points passed in
            self.score += ",".join(
                [str(question.category), str(score_to_add), str(possible_to_add), ""]
            )
            self.save()

    def show_exams(self):
        """
        Finds the previous quizzes marked as 'exam papers'.
        Returns a queryset of complete exams.
        """
        return Sitting.objects.filter(user=self.user, complete=True)

    def __str__(self):
        return self.user.username + " - " + self.score


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz):
        if quiz.random_order is True:
            question_set = quiz.question_set.all().select_subclasses().order_by("?")
        else:
            question_set = quiz.question_set.all().select_subclasses()

        question_set = [item.id for item in question_set]

        if len(question_set) == 0:
            raise ImproperlyConfigured(
                "Question set of the quiz is empty. "
                "Please configure questions properly"
            )

        if quiz.max_questions and quiz.max_questions < len(question_set):
            question_set = question_set[: quiz.max_questions]

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(
            choices=choice_list, widget=RadioSelect
        )

quiz/templates/quiz/addQuiz_list.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<h2>{% trans "Category list" %}</h2>

<ul>
  {% for cat in category_list %}
  <li>
	<a href="{% url 'quiz_category_list_matching' category_name=cat.category %}">
	  {{ cat.category }}
	</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

quiz/templates/quiz/category_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h2>{% trans "Category list" %}</h2>

<ul>
  {% for cat in category_list %}
  <li>
	<a href="{% url 'quiz_category_list_matching' category_name=cat.category %}">
	  {{ cat.category }}
  </a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

quiz/templates/quiz/main_page.html
<!-- filepath: /Users/owaisshaikh/Downloads/ByteSource/ByteSource/templates/quiz/main_page.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
</head>
<body>
    <h1>Welcome to the Main Page</h1>
</body>
</html>

quiz/templates/quiz/quiz_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{{ quiz.title }}
{% endblock %}
{% block content %}

<style>
  .head {
    display: inline;
    font-weight: bold;
    font-size: 30px;
  }

  .cat {
    display: inline;
  }

  .qtitle {
    border: 2px solid white;
    background-image: url('/static/img/topic.jpg');
    background-attachment: fixed;
    background-repeat: space;
    background-size: cover;
    height: 300px;
    padding: 30px;
    color: azure;
    text-align: bottom;
  }
  .category{
    background-image: url('/static/img/quiz.jpg');
    background-attachment: fixed;
    background-repeat: space;
    background-size: cover;
   border: 2px solid white;
   padding: 20px;
   
  }
  .cat{
    font-size: 30px;
    
  }
</style>

<body>
  <div class="qtitle">
    <h1>Topic : {{ quiz.title }}</h1>
  </div>
  <div class="category">
    <div class="head">{% trans "Category" %}</div>:<div class="cat">{{ quiz.category }}</div>
  </div>
  {% if quiz.single_attempt %}
  <h4>{% trans "You will only get one attempt at this quiz" %}.</h4>
  {% endif %}
  <p>{{ quiz.description }}</p>
  <p>
    <a class="btn btn-outline-success" href="{% url 'quiz_question' quiz_name=quiz.url %}" role="button">{% trans "Start quiz" %}</a>

    </a>
  </p>
</body>
{% endblock %}

quiz/templates/quiz/quiz_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load quiz_tags %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<style>
  .list {
    border: 2px solid white;
    background-image: url('/static/img/topic.jpg');
    background-attachment: fixed;
    background-repeat: space;
    background-size: cover;
    height: 300px;
    padding: 30px;
    color: azure;
    text-align: bottom;
  }
  table{
	padding: 2px;
  }
</style>
<div class="list">
	<h2>{% trans "LIST OF ALL THE QUIZZES" %}</h2>
</div>

    {% if quiz_list %}
		<table class="table table-bordered table-striped">

		  <thead>
			<tr>
			  <th>{% trans "Title" %}</th>
			  <th>{% trans "Category" %}</th>
			  <th>{% trans "Exam" %}</th>
			  <th>{% trans "Single attempt" %}</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>

        {% for quiz in quiz_list %}

  			<tr>
			  <td>{{ quiz.title }}</td>
			  <td>{{ quiz.category }}</td>
			  <td>{{ quiz.exam_paper }}</td>
			  <td>{{ quiz.single_attempt }}</td>
			  <td>
				<a href="{% url 'quiz_start_page' slug=quiz.url %}">
				  {% trans "View details" %}
				</a>
			</tr>

        {% endfor %}
		  </tbody>

		</table>

	{% else %}
        <p>{% trans "There are no available quizzes" %}.</p>
    {% endif %}
{% endblock %}

quiz/templates/quiz/redirect_to_admin.html
<!-- filepath: /Users/owaisshaikh/Downloads/ByteSource/ByteSource/quiz/templates/quiz/redirect_to_admin.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirect to Admin</title>
</head>
<body>
    <h1>Redirecting to Admin Page...</h1>
    <script>
        window.location.href = "/admin/";
    </script>
</body>
</html>

quiz/templates/quiz/sitting_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load quiz_tags %}
{% block title %}
{% trans "Result of" %} {{ sitting.quiz.title }} {% trans "for" %} {{ sitting.user }}
{% endblock %}

{% block content %}
<h2>{% trans "Quiz title" %}: {{ sitting.quiz.title }}</h2>
<h3>{% trans "Category" %}: {{ sitting.quiz.category }}</h3>
<p>{{ sitting.quiz.description }}</p>
<hr>
<p>{% trans "User" %}: {{ sitting.user }}</p>
<p>{% trans "Completed" %}: {{ sitting.end|date }}</p>
<p>{% trans "Score" %}: {{ sitting.get_percent_correct }}%</p>

<table class="table table-bordered table-striped">

  <thead>
	<tr>
	  <th>{% trans "Question" %}</th>
	  <th>{% trans "User answer" %}</th>
	  <th></th>
	  <th></th>
	</tr>
  </thead>

  <tbody>
{% for question in questions %}

	<tr>
      <td>
        {{ question.content }}
        {% if question.figure %}
        <div style="max-width: 100px;"><img src="{{ question.figure.url }}" alt="{{ question.figure }}"/></div>
        {% endif %}
      </td>
	  <td>{{ question|answer_choice_to_string:question.user_answer }}</td>
	  <td>
		{% if question.id in sitting.get_incorrect_questions %}
		  <p>{% trans "incorrect" %}</p>
		{% else %}
		  <p>{% trans "Correct" %}</p>
		{% endif %}
	  </td>
	  <td>
		<form action="" method="POST">{% csrf_token %}
		  <input type=hidden name="qid" value="{{ question.id }}">
		  <button type="submit" class="btn btn-warning">{% trans "Toggle whether correct" %}</button>
		</form>
	  </td>
	</tr>

{% endfor %}

  </tbody>

</table>
{% endblock %}

quiz/templates/quiz/sitting_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h2>{% trans "List of complete exams" %}</h2>
    {% if sitting_list %}

		<table class="table table-bordered table-striped">

		  <thead>
			<tr>
			  <th>{% trans "User" %}</th>
			  <th>{% trans "Quiz" %}</th>
			  <th>{% trans "Completed" %}</th>
			  <th>{% trans "Score" %}(%)</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<tr>
			  <form action="" method="GET">
				<td><input type="text" name="user_filter" /></td>
				<td><input type="text" name="quiz_filter" /></td>
				<td></td>
				<td></td>
				<td><button type="submit" class="btn btn-default">{% trans "Filter"%}</button></td>
			  </form>
			</tr>


        {% for sitting in sitting_list %}

			<tr>
			  <td>{{ sitting.user }}</td>
			  <td>{{ sitting.quiz }}</td>
			  <td>{{ sitting.end|date }}</td>
			  <td>{{ sitting.get_percent_correct }}</td>
			  <td>
				<a href="{% url 'quiz_marking_detail' pk=sitting.id %}">
				  {% trans "View details" %}
				</a>
			</tr>

        {% endfor %}

		  </tbody>

		</table>
    {% else %}
        <p>{% trans "There are no matching quizzes" %}.</p>
    {% endif %}
{% endblock %}